#801 + #831
xetdata/homebrew-xet-tools pull request #3
Opened 2022-08-05 09:04 UTC by port8080

Adds Post Install + Removes `xet [commands]` from issues

2022-08-09 16:40 UTC, bpronan requested changes
Changes look good! Take a look at the caveats block for post-install steps, but if it seems like too much work, what we have is just great!

One additional thing you'll need to do is backport the changes into the template file as well, so the next release will get your changes. It's at `.template/xet-tools.templ`. 

We use this template file in our CircleCI publishing step to automatically update the formula ruby file with the new binary's paths and shas.

2022-08-09 16:40 UTC, bpronan commented on xet-tools.rb
> +    # bin.install 'xet'
```suggestion
```

2022-08-09 16:40 UTC, bpronan commented on xet-tools.rb
> +    bin.echo 'Update your repo config to finish installation:
This works! Also, homebrew has [a caveats block](https://github.com/xetdata/xethub/pull/new/brian/cas-staging-support) where this could also go.

2022-08-10 07:48 UTC, port8080 commented
Made it:

```
def caveats
    <<~CAVEAT
      Update your repo config to finish installation:

      # Update global repo config
      $ git xet install
      
      More documentation here: https://hub.xetsvc.com/assets/docs
    CAVEAT
  end

  def install
    bin.install 'git-xet'
  end
```

2022-08-11 08:54 UTC, merged